# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudctx < Formula
  desc "A unified CLI for switching between cloud contexts"
  homepage "https://github.com/devops-chris/cloudctx"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.1.4/cloudctx_Darwin_x86_64.tar.gz"
      sha256 "1d3cdbda87a14a387e0a40fbc90e24bdd3d7d80c59cf54bb1451324514c6a283"

      def install
        bin.install "cloudctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.1.4/cloudctx_Darwin_arm64.tar.gz"
      sha256 "3831f04528d5486b7afff796c755ee910844eb7640ad7bfb8fc9337e01912570"

      def install
        bin.install "cloudctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.1.4/cloudctx_Linux_x86_64.tar.gz"
      sha256 "7d79a963e19c2bbed263c0b380a4399925b73b91a73773bfa568777af025c123"
      def install
        bin.install "cloudctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.1.4/cloudctx_Linux_arm64.tar.gz"
      sha256 "713decd61c50dee4f45b56c3c232ea615a6af33714abe6950ce618ce0947c5b5"
      def install
        bin.install "cloudctx"
      end
    end
  end

  test do
    system "#{bin}/cloudctx", "version"
  end
end
