# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudctx < Formula
  desc "A unified CLI for switching between cloud contexts"
  homepage "https://github.com/devops-chris/cloudctx"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.1/cloudctx_Darwin_x86_64.tar.gz"
      sha256 "83c5995b0b1a1ffc0d3e07652a8eb1a3248397ab15248cac57f63063a327758c"

      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.1/cloudctx_Darwin_arm64.tar.gz"
      sha256 "bcb2862437d5916803daccfb9d1871248b9be9167cde1939f2dff8e6747f4550"

      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.1/cloudctx_Linux_x86_64.tar.gz"
      sha256 "9d2abb7ba1ca056d7fc54d6b3eaf414c46c9e75a2ee3a1e2cb815756f146f601"
      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.1/cloudctx_Linux_arm64.tar.gz"
      sha256 "9ab36afe557644b89c07e10d92259c633ff3ddd323df552aeb92a6d7ca2453be"
      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
  end

  def caveats
    <<~EOS
      cloudctx works out of the box - no shell setup required.

      Optional: to make your shell prompt (Starship, powerlevel10k, etc.)
      show the active AWS profile, add the shell integration so AWS_PROFILE
      follows the profile you switch to:

        # zsh - add to ~/.zshrc
        eval "$(ctx shell-init zsh)"

        # bash - add to ~/.bashrc
        eval "$(ctx shell-init bash)"

      Then open a new shell. This is only needed for prompt display; all
      other functionality works without it.
    EOS
  end

  test do
    system "#{bin}/cloudctx", "version"
  end
end
