# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudctx < Formula
  desc "A unified CLI for switching between cloud contexts"
  homepage "https://github.com/devops-chris/cloudctx"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.3/cloudctx_Darwin_x86_64.tar.gz"
      sha256 "971c16e5380ce61476a543c7ab10cc99683e9779985b52262ac12bd5893bcb43"

      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.3/cloudctx_Darwin_arm64.tar.gz"
      sha256 "d5578a4f5fab9bc097797e77d7a692a32818bf92a8b7d4acd8026125aa56625d"

      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.3/cloudctx_Linux_x86_64.tar.gz"
      sha256 "e543f227c3366de150de82a617cb28e1e3fb933eb97be015502659561593efb2"
      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/cloudctx/releases/download/v0.5.3/cloudctx_Linux_arm64.tar.gz"
      sha256 "90359842bd00cb998386f421c6fe81e85fc649ba1d3528e324c0e90b0b15493b"
      define_method(:install) do
        bin.install "cloudctx"
        bin.install_symlink "cloudctx" => "ctx"
      end
    end
  end

  def caveats
    <<~EOS
      cloudctx works out of the box - no shell setup required.

      Optional: to make your shell prompt (Starship, powerlevel10k, etc.)
      show the active AWS profile, add the shell integration so AWS_PROFILE
      follows the profile you switch to:

        # zsh - add to ~/.zshrc
        eval "$(ctx shell-init zsh)"

        # bash - add to ~/.bashrc
        eval "$(ctx shell-init bash)"

      Then open a new shell. This is only needed for prompt display; all
      other functionality works without it.
    EOS
  end

  test do
    system "#{bin}/cloudctx", "version"
  end
end
