# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockr < Formula
  desc "A simple CLI for managing secrets in AWS SSM Parameter Store"
  homepage "https://github.com/devops-chris/lockr"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/devops-chris/lockr/releases/download/v0.2.0/lockr_0.2.0_darwin_amd64.tar.gz"
      sha256 "8bd33268fce42ca2dcf860b0e27276374f484a929549ee9f6f043f5f18b3396e"

      def install
        bin.install "lockr"
      end
    end
    on_arm do
      url "https://github.com/devops-chris/lockr/releases/download/v0.2.0/lockr_0.2.0_darwin_arm64.tar.gz"
      sha256 "8c518c5620593f7e91d878dbb5cb950b8e4814e5585ef96ad2e12df26679b0d9"

      def install
        bin.install "lockr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devops-chris/lockr/releases/download/v0.2.0/lockr_0.2.0_linux_amd64.tar.gz"
        sha256 "f4c532e4ba1404ec9855f5b6aa4b4d19663665c6cb234d97ea5b8bda59739226"

        def install
          bin.install "lockr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devops-chris/lockr/releases/download/v0.2.0/lockr_0.2.0_linux_arm64.tar.gz"
        sha256 "935bf7679587813cb07b542a82d91df2447c0351ad1889cddbbed98c0eb62720"

        def install
          bin.install "lockr"
        end
      end
    end
  end

  test do
    system "#{bin}/lockr", "version"
  end
end
