# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockr < Formula
  desc "A simple CLI for managing secrets in AWS SSM Parameter Store"
  homepage "https://github.com/devops-chris/lockr"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/devops-chris/lockr/releases/download/v0.1.0/lockr_0.1.0_darwin_amd64.tar.gz"
      sha256 "4fe1807ba5f0882b18974eef57d6a54e636c260c658fe53236f33a9676487db1"

      def install
        bin.install "lockr"
      end
    end
    on_arm do
      url "https://github.com/devops-chris/lockr/releases/download/v0.1.0/lockr_0.1.0_darwin_arm64.tar.gz"
      sha256 "fd44c7b23629e6418d3ada1ec544ebc1eb596a8177fe82d347bf6f43f05a10df"

      def install
        bin.install "lockr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devops-chris/lockr/releases/download/v0.1.0/lockr_0.1.0_linux_amd64.tar.gz"
        sha256 "7c3aee20011e3427e87fc3a996c202b77169fcb2a5f2ec321031370307d7c16b"

        def install
          bin.install "lockr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/devops-chris/lockr/releases/download/v0.1.0/lockr_0.1.0_linux_arm64.tar.gz"
        sha256 "671ef9b9264fc6145c652806cfc0f5931a73e9d424ba78c66edf59e998c24a79"

        def install
          bin.install "lockr"
        end
      end
    end
  end

  test do
    system "#{bin}/lockr", "version"
  end
end
