# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Platformr < Formula
  desc "Configurable developer self-service platform CLI"
  homepage "https://github.com/devops-chris/platformr"
  version "0.1.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/devops-chris/platformr/releases/download/v0.1.22/platformr_0.1.22_darwin_amd64.tar.gz"
      sha256 "b46e755765e76de62a7f7f5b413cd7ea1ddc70e42c30e0a18cc14fb718d3d5ff"

      define_method(:install) do
        bin.install "platformr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/devops-chris/platformr/releases/download/v0.1.22/platformr_0.1.22_darwin_arm64.tar.gz"
      sha256 "0eaa503cf982ef52b623c946a7c6e2b11bfb298ea9bf80a96f3b14a150e2548a"

      define_method(:install) do
        bin.install "platformr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/platformr/releases/download/v0.1.22/platformr_0.1.22_linux_amd64.tar.gz"
      sha256 "f9af973f5031e463e1204d9d5a5f889b0acb3595eda5090432d516dacfa411ce"
      define_method(:install) do
        bin.install "platformr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devops-chris/platformr/releases/download/v0.1.22/platformr_0.1.22_linux_arm64.tar.gz"
      sha256 "40b30b16d5b77f13c46a4dfbba40d45948b516465fa9297515d1c6b420763cda"
      define_method(:install) do
        bin.install "platformr"
      end
    end
  end

  test do
    system "#{bin}/platformr", "version"
  end
end
